# Generated by Django 4.2.4 on 2023-08-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('toys', 'toys'), ('foods', 'foods'), ('cosmetics', 'cosmetics'), ('fashion', 'fashion')], max_length=9)),
                ('slug', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='multi_upload.product')),
            ],
        ),
    ]
