# Generated by Django 4.2.4 on 2023-08-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x0000025BC37D0DC0>'),
        ),
    ]
