# Generated by Django 4.2.4 on 2023-08-30 04:59

from django.db import migrations, models
import multi_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0003_remove_images_description_remove_images_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.FileField(blank=True, upload_to=multi_upload.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='images',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
