# Generated by Django 4.2.4 on 2023-08-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0003_alter_productsimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.ImageField(upload_to='None'),
        ),
    ]
