# Generated by Django 4.2.4 on 2023-08-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0004_alter_productsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsimage',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.fields.CharField>'),
        ),
    ]
