# Generated by Django 4.2.4 on 2023-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0006_alter_images_img_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
