# Generated by Django 4.2.4 on 2023-09-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0008_remove_restaurant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
