# Generated by Django 5.0.3 on 2024-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0009_alter_restaurant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('promo_image', models.ImageField(upload_to='origin_directory_path')),
                ('vendor_image', models.ImageField(upload_to='sticker_directory_path')),
            ],
        ),
    ]
