# Generated by Django 5.0.3 on 2024-03-07 18:52

import multi_upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0010_promosticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promosticker',
            name='promo_image',
            field=models.ImageField(upload_to=multi_upload.models.sticker_directory_path),
        ),
        migrations.AlterField(
            model_name='promosticker',
            name='vendor_image',
            field=models.ImageField(blank=True, null=True, upload_to=multi_upload.models.origin_directory_path),
        ),
    ]
