# Generated by Django 5.0.3 on 2024-03-07 19:30

import django.db.models.deletion
import multi_upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0011_alter_promosticker_promo_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promosticker',
            name='vendor_image',
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_image', models.FileField(blank=True, null=True, upload_to=multi_upload.models.origin_directory_path)),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_image', to='multi_upload.promosticker')),
            ],
        ),
    ]
