# Generated by Django 5.0.3 on 2024-04-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0017_vendorimage_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promosticker',
            name='promo_image',
            field=models.ImageField(blank=True, null=True, upload_to='stickers'),
        ),
    ]
