# Generated by Django 5.0.3 on 2024-04-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_upload', '0019_tags_vendor_vendorimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_tag', to='multi_upload.tags'),
        ),
        migrations.AlterField(
            model_name='vendorimages',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors_images', to='multi_upload.vendor'),
        ),
    ]
